- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - scorecard-test
    - spec-crd-validated
    image: quay.io/operator-framework/scorecard-test:v1.42.2
    labels:
      suite: intermediate
      test: spec-crd-validated-test
- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - scorecard-test
    - spec-has-workload
    image: quay.io/operator-framework/scorecard-test:v1.42.2
    labels:
      suite: intermediate
      test: spec-has-workload-test
