- op: add
  path: /stages/1/tests/-
  value:
    entrypoint:
    - scorecard-test
    - olm-crds-deployed
    image: quay.io/operator-framework/scorecard-test:v1.42.2
    labels:
      suite: olm
      test: olm-crds-deployed-test
- op: add
  path: /stages/1/tests/-
  value:
    entrypoint:
    - scorecard-test
    - olm-bundle-deployment
    image: quay.io/operator-framework/scorecard-test:v1.42.2
    labels:
      suite: olm
      test: olm-bundle-deployment-test
