apiVersion: onboarding.stderr.at/v1beta1
kind: ProjectOnboarding
metadata:
  name: team-gamma-dev
spec:
  namespaces:
    - name: team-gamma-dev
      projectSize: small
      overwriteTshirt: true
      resourceQuotas:
        enabled: true
