//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalSettingsSpec) DeepCopyInto(out *AdditionalSettingsSpec) {
	*out = *in
	if in.EnableClusterMonitoring != nil {
		in, out := &in.EnableClusterMonitoring, &out.EnableClusterMonitoring
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make([]NamespaceLabel, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalSettingsSpec.
func (in *AdditionalSettingsSpec) DeepCopy() *AdditionalSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(AdditionalSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDPolicySpec) DeepCopyInto(out *ArgoCDPolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDPolicySpec.
func (in *ArgoCDPolicySpec) DeepCopy() *ArgoCDPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDProjectSpec) DeepCopyInto(out *ArgoCDProjectSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.SourceRepos != nil {
		in, out := &in.SourceRepos, &out.SourceRepos
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SourceNamespaces != nil {
		in, out := &in.SourceNamespaces, &out.SourceNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]GitOpsDestinationSpec, len(*in))
		copy(*out, *in)
	}
	if in.OIDCGroups != nil {
		in, out := &in.OIDCGroups, &out.OIDCGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]ArgoCDRoleSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDProjectSpec.
func (in *ArgoCDProjectSpec) DeepCopy() *ArgoCDProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDRoleSpec) DeepCopyInto(out *ArgoCDRoleSpec) {
	*out = *in
	if in.OIDCGroups != nil {
		in, out := &in.OIDCGroups, &out.OIDCGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FullAccess != nil {
		in, out := &in.FullAccess, &out.FullAccess
		*out = new(bool)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]ArgoCDPolicySpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDRoleSpec.
func (in *ArgoCDRoleSpec) DeepCopy() *ArgoCDRoleSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomNetworkPolicySpec) DeepCopyInto(out *CustomNetworkPolicySpec) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.IngressRules != nil {
		in, out := &in.IngressRules, &out.IngressRules
		*out = make([]NetworkPolicyRuleSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EgressRules != nil {
		in, out := &in.EgressRules, &out.EgressRules
		*out = make([]NetworkPolicyRuleSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomNetworkPolicySpec.
func (in *CustomNetworkPolicySpec) DeepCopy() *CustomNetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CustomNetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultPoliciesSpec) DeepCopyInto(out *DefaultPoliciesSpec) {
	*out = *in
	if in.AllowFromIngress != nil {
		in, out := &in.AllowFromIngress, &out.AllowFromIngress
		*out = new(bool)
		**out = **in
	}
	if in.AllowFromMonitoring != nil {
		in, out := &in.AllowFromMonitoring, &out.AllowFromMonitoring
		*out = new(bool)
		**out = **in
	}
	if in.AllowKubeAPIServer != nil {
		in, out := &in.AllowKubeAPIServer, &out.AllowKubeAPIServer
		*out = new(bool)
		**out = **in
	}
	if in.AllowToDNS != nil {
		in, out := &in.AllowToDNS, &out.AllowToDNS
		*out = new(bool)
		**out = **in
	}
	if in.DenyAllEgress != nil {
		in, out := &in.DenyAllEgress, &out.DenyAllEgress
		*out = new(bool)
		**out = **in
	}
	if in.DenyAllIngress != nil {
		in, out := &in.DenyAllIngress, &out.DenyAllIngress
		*out = new(bool)
		**out = **in
	}
	if in.AllowFromSameNamespace != nil {
		in, out := &in.AllowFromSameNamespace, &out.AllowFromSameNamespace
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultPoliciesSpec.
func (in *DefaultPoliciesSpec) DeepCopy() *DefaultPoliciesSpec {
	if in == nil {
		return nil
	}
	out := new(DefaultPoliciesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressIPSpec) DeepCopyInto(out *EgressIPSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.IPs != nil {
		in, out := &in.IPs, &out.IPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressIPSpec.
func (in *EgressIPSpec) DeepCopy() *EgressIPSpec {
	if in == nil {
		return nil
	}
	out := new(EgressIPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsDestinationSpec) DeepCopyInto(out *GitOpsDestinationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsDestinationSpec.
func (in *GitOpsDestinationSpec) DeepCopy() *GitOpsDestinationSpec {
	if in == nil {
		return nil
	}
	out := new(GitOpsDestinationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsSpec) DeepCopyInto(out *GitOpsSpec) {
	*out = *in
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]GitOpsDestinationSpec, len(*in))
		copy(*out, *in)
	}
	if in.AllowedSourceRepos != nil {
		in, out := &in.AllowedSourceRepos, &out.AllowedSourceRepos
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedOIDCGroups != nil {
		in, out := &in.AllowedOIDCGroups, &out.AllowedOIDCGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedSourceNamespaces != nil {
		in, out := &in.AllowedSourceNamespaces, &out.AllowedSourceNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsSpec.
func (in *GitOpsSpec) DeepCopy() *GitOpsSpec {
	if in == nil {
		return nil
	}
	out := new(GitOpsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPBlockSpec) DeepCopyInto(out *IPBlockSpec) {
	*out = *in
	if in.Except != nil {
		in, out := &in.Except, &out.Except
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPBlockSpec.
func (in *IPBlockSpec) DeepCopy() *IPBlockSpec {
	if in == nil {
		return nil
	}
	out := new(IPBlockSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitRangeContainerSpec) DeepCopyInto(out *LimitRangeContainerSpec) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(ResourceAmountSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(ResourceAmountSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(ResourceAmountSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultRequest != nil {
		in, out := &in.DefaultRequest, &out.DefaultRequest
		*out = new(ResourceAmountSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitRangeContainerSpec.
func (in *LimitRangeContainerSpec) DeepCopy() *LimitRangeContainerSpec {
	if in == nil {
		return nil
	}
	out := new(LimitRangeContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitRangePVCSpec) DeepCopyInto(out *LimitRangePVCSpec) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(StorageAmountSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(StorageAmountSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitRangePVCSpec.
func (in *LimitRangePVCSpec) DeepCopy() *LimitRangePVCSpec {
	if in == nil {
		return nil
	}
	out := new(LimitRangePVCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitRangePodSpec) DeepCopyInto(out *LimitRangePodSpec) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(ResourceAmountSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(ResourceAmountSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitRangePodSpec.
func (in *LimitRangePodSpec) DeepCopy() *LimitRangePodSpec {
	if in == nil {
		return nil
	}
	out := new(LimitRangePodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitRangeSpec) DeepCopyInto(out *LimitRangeSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(LimitRangePodSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(LimitRangeContainerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(LimitRangePVCSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitRangeSpec.
func (in *LimitRangeSpec) DeepCopy() *LimitRangeSpec {
	if in == nil {
		return nil
	}
	out := new(LimitRangeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalAdminGroupSpec) DeepCopyInto(out *LocalAdminGroupSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalAdminGroupSpec.
func (in *LocalAdminGroupSpec) DeepCopy() *LocalAdminGroupSpec {
	if in == nil {
		return nil
	}
	out := new(LocalAdminGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceLabel) DeepCopyInto(out *NamespaceLabel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceLabel.
func (in *NamespaceLabel) DeepCopy() *NamespaceLabel {
	if in == nil {
		return nil
	}
	out := new(NamespaceLabel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSpec) DeepCopyInto(out *NamespaceSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Offboard != nil {
		in, out := &in.Offboard, &out.Offboard
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalSettings != nil {
		in, out := &in.AdditionalSettings, &out.AdditionalSettings
		*out = new(AdditionalSettingsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OverwriteTshirt != nil {
		in, out := &in.OverwriteTshirt, &out.OverwriteTshirt
		*out = new(bool)
		**out = **in
	}
	if in.ResourceQuotas != nil {
		in, out := &in.ResourceQuotas, &out.ResourceQuotas
		*out = new(ResourceQuotaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LimitRanges != nil {
		in, out := &in.LimitRanges, &out.LimitRanges
		*out = new(LimitRangeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultPolicies != nil {
		in, out := &in.DefaultPolicies, &out.DefaultPolicies
		*out = new(DefaultPoliciesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkPolicies != nil {
		in, out := &in.NetworkPolicies, &out.NetworkPolicies
		*out = make([]CustomNetworkPolicySpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LocalAdminGroup != nil {
		in, out := &in.LocalAdminGroup, &out.LocalAdminGroup
		*out = new(LocalAdminGroupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EgressIPs != nil {
		in, out := &in.EgressIPs, &out.EgressIPs
		*out = new(EgressIPSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ArgoCDProjects != nil {
		in, out := &in.ArgoCDProjects, &out.ArgoCDProjects
		*out = make([]ArgoCDProjectSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSpec.
func (in *NamespaceSpec) DeepCopy() *NamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceStatus) DeepCopyInto(out *NamespaceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceStatus.
func (in *NamespaceStatus) DeepCopy() *NamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(NamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyPeerSpec) DeepCopyInto(out *NetworkPolicyPeerSpec) {
	*out = *in
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.IPBlock != nil {
		in, out := &in.IPBlock, &out.IPBlock
		*out = new(IPBlockSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyPeerSpec.
func (in *NetworkPolicyPeerSpec) DeepCopy() *NetworkPolicyPeerSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyPeerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyPortSpec) DeepCopyInto(out *NetworkPolicyPortSpec) {
	*out = *in
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyPortSpec.
func (in *NetworkPolicyPortSpec) DeepCopy() *NetworkPolicyPortSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyPortSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyRuleSpec) DeepCopyInto(out *NetworkPolicyRuleSpec) {
	*out = *in
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = make([]NetworkPolicyPeerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]NetworkPolicyPortSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyRuleSpec.
func (in *NetworkPolicyRuleSpec) DeepCopy() *NetworkPolicyRuleSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectOnboarding) DeepCopyInto(out *ProjectOnboarding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectOnboarding.
func (in *ProjectOnboarding) DeepCopy() *ProjectOnboarding {
	if in == nil {
		return nil
	}
	out := new(ProjectOnboarding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectOnboarding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectOnboardingList) DeepCopyInto(out *ProjectOnboardingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProjectOnboarding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectOnboardingList.
func (in *ProjectOnboardingList) DeepCopy() *ProjectOnboardingList {
	if in == nil {
		return nil
	}
	out := new(ProjectOnboardingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectOnboardingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectOnboardingSpec) DeepCopyInto(out *ProjectOnboardingSpec) {
	*out = *in
	if in.GitOps != nil {
		in, out := &in.GitOps, &out.GitOps
		*out = new(GitOpsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]NamespaceSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectOnboardingSpec.
func (in *ProjectOnboardingSpec) DeepCopy() *ProjectOnboardingSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectOnboardingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectOnboardingStatus) DeepCopyInto(out *ProjectOnboardingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]NamespaceStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectOnboardingStatus.
func (in *ProjectOnboardingStatus) DeepCopy() *ProjectOnboardingStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectOnboardingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceAmountSpec) DeepCopyInto(out *ResourceAmountSpec) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(string)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceAmountSpec.
func (in *ResourceAmountSpec) DeepCopy() *ResourceAmountSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceAmountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaLimitSpec) DeepCopyInto(out *ResourceQuotaLimitSpec) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(string)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(string)
		**out = **in
	}
	if in.EphemeralStorage != nil {
		in, out := &in.EphemeralStorage, &out.EphemeralStorage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaLimitSpec.
func (in *ResourceQuotaLimitSpec) DeepCopy() *ResourceQuotaLimitSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaLimitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaRequestSpec) DeepCopyInto(out *ResourceQuotaRequestSpec) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(string)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(string)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(string)
		**out = **in
	}
	if in.EphemeralStorage != nil {
		in, out := &in.EphemeralStorage, &out.EphemeralStorage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaRequestSpec.
func (in *ResourceQuotaRequestSpec) DeepCopy() *ResourceQuotaRequestSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaSpec) DeepCopyInto(out *ResourceQuotaSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(string)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(string)
		**out = **in
	}
	if in.EphemeralStorage != nil {
		in, out := &in.EphemeralStorage, &out.EphemeralStorage
		*out = new(string)
		**out = **in
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(int32)
		**out = **in
	}
	if in.ReplicationControllers != nil {
		in, out := &in.ReplicationControllers, &out.ReplicationControllers
		*out = new(int32)
		**out = **in
	}
	if in.ResourceQuotas != nil {
		in, out := &in.ResourceQuotas, &out.ResourceQuotas
		*out = new(int32)
		**out = **in
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(int32)
		**out = **in
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = new(int32)
		**out = **in
	}
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = new(int32)
		**out = **in
	}
	if in.PersistentVolumeClaims != nil {
		in, out := &in.PersistentVolumeClaims, &out.PersistentVolumeClaims
		*out = new(int32)
		**out = **in
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(ResourceQuotaLimitSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(ResourceQuotaRequestSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageClasses != nil {
		in, out := &in.StorageClasses, &out.StorageClasses
		*out = make([]StorageClassQuota, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaSpec.
func (in *ResourceQuotaSpec) DeepCopy() *ResourceQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAmountSpec) DeepCopyInto(out *StorageAmountSpec) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAmountSpec.
func (in *StorageAmountSpec) DeepCopy() *StorageAmountSpec {
	if in == nil {
		return nil
	}
	out := new(StorageAmountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClassQuota) DeepCopyInto(out *StorageClassQuota) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClassQuota.
func (in *StorageClassQuota) DeepCopy() *StorageClassQuota {
	if in == nil {
		return nil
	}
	out := new(StorageClassQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TShirtSize) DeepCopyInto(out *TShirtSize) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TShirtSize.
func (in *TShirtSize) DeepCopy() *TShirtSize {
	if in == nil {
		return nil
	}
	out := new(TShirtSize)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TShirtSize) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TShirtSizeList) DeepCopyInto(out *TShirtSizeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TShirtSize, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TShirtSizeList.
func (in *TShirtSizeList) DeepCopy() *TShirtSizeList {
	if in == nil {
		return nil
	}
	out := new(TShirtSizeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TShirtSizeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TShirtSizeSpec) DeepCopyInto(out *TShirtSizeSpec) {
	*out = *in
	if in.ResourceQuotas != nil {
		in, out := &in.ResourceQuotas, &out.ResourceQuotas
		*out = new(ResourceQuotaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LimitRanges != nil {
		in, out := &in.LimitRanges, &out.LimitRanges
		*out = new(LimitRangeSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TShirtSizeSpec.
func (in *TShirtSizeSpec) DeepCopy() *TShirtSizeSpec {
	if in == nil {
		return nil
	}
	out := new(TShirtSizeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TShirtSizeStatus) DeepCopyInto(out *TShirtSizeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TShirtSizeStatus.
func (in *TShirtSizeStatus) DeepCopy() *TShirtSizeStatus {
	if in == nil {
		return nil
	}
	out := new(TShirtSizeStatus)
	in.DeepCopyInto(out)
	return out
}
