{{- $version := .Chart.AppVersion }}
{{- $catalogImage := .Values.catalog.image | default (printf "quay.io/tjungbau/project-onboarding-operator-catalog:v%s" $version) }}
{{- $startingCSV := .Values.subscription.startingCSV | default (printf "project-onboarding-operator.v%s" $version) }}
{{- if $catalogImage }}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ .Values.catalog.name }}
  namespace: {{ .Values.marketplaceNamespace }}
spec:
  displayName: {{ .Values.catalog.displayName }}
  publisher: {{ .Values.catalog.publisher }}
  sourceType: grpc
  image: {{ $catalogImage }}
  updateStrategy:
    registryPoll:
      interval: 45m
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.subscription.name }}
  namespace: {{ .Values.operatorNamespace }}
spec:
  channel: {{ .Values.subscription.channel }}
  name: project-onboarding-operator
  source: {{ .Values.catalog.name }}
  sourceNamespace: {{ .Values.marketplaceNamespace }}
  startingCSV: {{ $startingCSV }}
  installPlanApproval: {{ .Values.subscription.installPlanApproval }}
{{- end }}
