# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/project-onboarding-operator.clusterserviceversion.yaml
- ../default
- ../prometheus
- ../openshift
- ../samples
- ../scorecard

replacements:
  - source:
      kind: Secret
      name: controller-manager-metrics-reader-token
      fieldPath: metadata.name
    targets:
      - select:
          kind: ServiceMonitor
          name: controller-manager-metrics-monitor
        fieldPaths:
          - spec.endpoints.0.authorization.credentials.name
  - source:
      kind: ServiceAccount
      name: controller-manager
      fieldPath: metadata.name
    targets:
      - select:
          kind: Secret
          name: controller-manager-metrics-reader-token
        fieldPaths:
          - metadata.annotations.[kubernetes.io/service-account.name]

patches:
- path: patches/icon.yaml
  target:
    group: operators.coreos.com
    version: v1alpha1
    kind: ClusterServiceVersion
    name: project-onboarding-operator.v0.0.0
- path: patches/manager_hostusers_patch.yaml
  target:
    kind: Deployment
    name: controller-manager
- path: ../openshift/webhook_service_tls_patch.yaml
  target:
    kind: Service
    name: project-onboarding-operator-webhook-service
- path: ../openshift/webhook_cabundle_patch.yaml
  target:
    kind: ValidatingWebhookConfiguration
    name: project-onboarding-operator-validating-webhook-configuration
